security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_signin
                check_path: app_signin
                default_target_path: app_dashboard
                enable_csrf: true
                username_parameter: email  # Spécifie explicitement le paramètre email
                password_parameter: password  # Spécifie explicitement le paramètre password
            logout:
                path: app_logout
                target: app_signin
                invalidate_session: true

    access_control:
        - { path: ^/signin, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ROLE_EMPLOYEE, ROLE_ADMIN, ROLE_RESPONSABLE] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10