controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_google_auth:
    path: /google/auth
    controller: App\Controller\ActivityController::googleAuth
    methods: [GET]
