# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    azure.blob.connection_string: 'DefaultEndpointsProtocol=https;AccountName=globaltravelst;AccountKey=BZV+gsukTi/C5g8qpM5GeUf1Fy4klSrbJkiASacXlmzhEHv2ZSUe5qSU5bUaFj6+chX+fyjCBkHT+AStlGTwIQ==;EndpointSuffix=core.windows.net'
    azure.blob.container_name: 'globaltravelstorage'
    azure.blob.disable_ssl_verification: true
    env(NOMINATIM_USER_AGENT): 'GlobalTravelApp/1.0'
    akismet.api_key: '8c085842ad83'
    akismet.blog_url: 'http://127.0.0.1:8000'
    google_client_secret_path: '%kernel.project_dir%/config/google_client_secret.json'
    google_calendar_id: 'primary'
    facebook_client_id: '%env(FB_ID)%'
    facebook_client_secret: '%env(FB_SECRET)%'

    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    App\Service\AzureBlobService:
            arguments:
                $connectionString: '%azure.blob.connection_string%'
                $containerName: '%azure.blob.container_name%'
                $disableSslVerification: '%azure.blob.disable_ssl_verification%'
    App\Service\CityDataProvider:
        arguments:
            $userAgent: '%env(NOMINATIM_USER_AGENT)%'
            $cache: '@cache.app'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\HotelController:
        arguments:
            $logger: '@monolog.logger'
            $csrfTokenManager: '@security.csrf.token_manager'
            $httpClient: '@http_client'
    

    App\Service\AkismetSpamChecker:
        arguments:
            $akismetApiKey: '%akismet.api_key%'  # ← Nom corrigé
            $akismetBlogUrl: '%akismet.blog_url%' # ← Nom corrigé
            $httpClient: '@http_client'
            $logger: '@logger' # Ajouter cette ligne

    App\Service\GoogleCalendarService:  
        arguments:
            $requestStack: '@request_stack'
            $googleClientSecretPath: '%kernel.project_dir%/config/google_client_secret.json'
            

    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    
